spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spr_secur_drafting
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
  mail:
    host: localhost
    port: 1025
    username: yassine
    password: yassine
    properties:
      mail:
        smtp:
          trust: "*"
        auth: true
        starttls:
          enabled: true
        connectiontimeout: 5000
        timeout: 3000
        writetimeout: 5000

application:
  security:
    jwt:
      secret-key: ee38f3e5cd0da7cfddf06edfa8dae4502c2d1c23ad70466c9093380ec9293ee9
      expiration: 86400000
  mailing:
    frontend:
      activation-url: http://localhost:4200/activate-account
  file:
    uploads:
      output-photos-folder: ./uploads
  cors:
    origins: http://localhost:4200,http://localhost:8080,http://vps_ip:8080,http://vps_ip:8088

server:
  port: 8088